[book]
authors = ["EvilBit-Labs"]
language = "en"
src = "src"
title = "DaemonEye Documentation"
description = "DaemonEye User Documentation"

[build]
build-dir = "book"
create-missing = true

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/EvilBit-Labs/daemoneye"
edit-url-template = "https://github.com/EvilBit-Labs/daemoneye/edit/main/docs/src/{path}"
additional-css = ["whichlang.css"]
additional-js = ["mermaid-init.js", "whichlang.js", "mermaid.min.js"]

[output.html.fold]
enable = true
level = 1

[output.html.playground]
runnable = false

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.toc]
command = "mdbook-toc"
marker = "[TOC]"
renderer = ["html"]


[preprocessor.tabs]
command = "mdbook-tabs"

[preprocessor.yml-header]
